gain_linear_velocity_x: 0.2
gain_linear_velocity_y: 0.2
gain_angular_velocity_z: 1.0

maximum_linear_velocity_x: 0.3
maximum_linear_velocity_y: 0.2
maximum_angular_velocity_z: 0.2

threshold_linear_velocity_x: 0.002
threshold_linear_velocity_y: 0.002
threshold_angular_velocity_z: 0.005

goal_threshold_x: 0.01
goal_threshold_y: 0.01
goal_threshold_theta: 0.05

check_initial_limits: false
initial_maximum_distance_x: 2.5
initial_minimum_distance_x: 0.5
initial_maximum_distance_y: 2.5
initial_minimum_distance_y: 0

minimum_relative_linear_velocity_between_robot_and_goal: 0.001
minimum_relative_angular_velocity_between_robot_and_goal: 0.002

initial_maximum_arc: 3.1416
initial_maximum_yaw: 1

publish_debug_frames: true
offset_for_heading_adjustment: 0.4
offset_for_overshoot: 0.5

tf_timeout: 5
free_goal_velocity: true

check_robot_is_moving_to_goal: false
robot_moving_to_goal_delay: 3
robot_moving_to_goal_averaging_time: 1.0
