version: "3.1"

services:

    ### S&P ###
    sp:
        image: docker.ramp.eu/opil/opil.sw.sp.central:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./annotations.ini:/annotations.ini:ro
            - ./demo_map.yaml:/map.yaml:ro
            - ./demo_map_reduced.png:/map.png:ro
            - ./topology.launch:/topology.launch:ro
        environment:
            - HOST=sp
            - DISPLAY=$DISPLAY
        ports: 
            - "39002:39002"


